### ISSUE TITLE
Sample Understand  schedule diverges from Trello template

### ISSUE THREAD

**Issue by ericwbailey** [thoughtbot/design-sprint#100]
- [Understand schedule](https://github.com/thoughtbot/design-sprint/blob/master/1-Understand/Schedule.md)
- [Trello template](https://trello.com/b/lMmuSlkP/project-template-product-design-sprint)

These exercises aren't listed on Trello and are missing detail as to how to conduct them (see https://github.com/thoughtbot/design-sprint/issues/75):

- Definitions: The Business & The Customer
- Definitions: The problem, The Value Prop, Success
- Business Model Canvas
- Lightning Demos
- Expert Perspectives

It isn't immediately clear which resource is more up-to-date, or where these exercises fit in the overall scheme of things. I'd recommend maybe collecting these and creating an optional exercises doc, provided the Trello template is the more up-to-date resource. If not, add these to Trello.

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
