### ISSUE TITLE
Understand phase sample schedule should have the critical path!

### ISSUE THREAD

**Issue by ericwbailey** [thoughtbot/design-sprint#102]
https://github.com/thoughtbot/design-sprint/blob/master/1-Understand/Schedule.md

Note to self to fix on Friday.

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
