### ISSUE TITLE
Some proposed Understand schedule items don't have content/definitions

### ISSUE THREAD

**Issue by ericwbailey** [thoughtbot/design-sprint#103]
https://github.com/thoughtbot/design-sprint/blob/master/1-Understand/Schedule.md

- Definitions: The Business & The Customer
- Definitions: The problem, The Value Prop, Success
- Business Model Canvas
- Lightning Demos

Not so great to discover the day of :\

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
