### ISSUE TITLE
More detail around Diverge "Identify and diagram the critical path for the prototype"

### ISSUE THREAD

**Issue by ericwbailey** [thoughtbot/design-sprint#104]
https://github.com/thoughtbot/design-sprint/blob/master/2-Diverge/Schedule.md

This step needs more detail. Right now it feels like a duplicate of the Day 1 recap, and there isn't enough information on why it is broken out as a separate step.

Additionally, it could use more detail on how to break it down from a user's perspective, and how this critical path diagramming differs from the Understand critical path.

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
