### ISSUE TITLE
Difficult to Locate User Testing User Request Template and Gift Card Amount

### ISSUE THREAD

**Issue by knittingarch** [thoughtbot/design-sprint#105]
In looking to find additional testers for user testing for MotaMeet, I was unable to locate the information I needed in this repo.

Initially, I went to the handbook after asking @KurodaSteph if she knew the going rate for user interviews.  I searched within the handbook under `designing`, `marketing`, `sales`, and a few others before giving up on the handbook.

I then tried the TB Search, but was presented with a list of previous design sprints in Hub.

I found @tysongach in the kitchen and asked him for some guidance and he recommended this `design-sprint` repo.  I came here expecting to find templates and compensation information under `5-Test`, but there was only a case study and links to create a survey.

Then I went to thoughbot.com, hoping to find the information I needed but I went to the wrong section.  I went to Services > Design Sprints.

It turns out that the information I needed was at [Test Usability](https://thoughtbot.com/playbook/designing/test-usability).

It would be really helpful if we had one source of truth for this information in github and online.

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
