### ISSUE TITLE
Give the docs a better design 

### ISSUE THREAD

**Issue by kylefiedler** [thoughtbot/design-sprint#56]
Thinking something like transforming this to a middleman app and using the robots css

**Comment by cllns** [comment]
Have you considered using [softcover.io](softcover.io)? 

It lets you write markdown and output it as HTML, epub, PDF, mobi.

I've never used it, but it seems good. It was used for the most recent version of the Rails Tutorial (and also written by the author, Michael Hartl)

Could be neat to have this as a PDF!

**Comment by kylefiedler** [comment]
@cllns I'm not sure we wnt a PDF version. I was more thinking a gh-pages branch with some nice styles.
