### ISSUE TITLE
Add Understand exercise to review Google Keyword Planner

### ISSUE THREAD

**Issue by croaky** [thoughtbot/design-sprint#87]
_Job-to-be-done_

**When I** have to decide between market/user segments for my product
**I want to** be able to gauge size of market and cost to acquire those users
**So that** I can plan my rollout and pick relevant vocabulary

Examples:
- home improvement app - house painters or plumbers first?
- code linter - java or objective-c as the next linter to write and rollout?

https://github.com/thoughtbot/design-sprint/tree/master/1-Understand
https://adwords.google.com/ko/KeywordPlanner/Home

**Comment by croaky** [comment]
Could alternatively use Facebook or Twitter ad platforms depending on context. Google if looking for intent to purchase, language.

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
