### ISSUE TITLE
Add customer acquisition channel analysis exercise to Diverge phase

### ISSUE THREAD

**Issue by croaky** [thoughtbot/design-sprint#88]
_Job-to-be-done_

**When I** am determining my critical path
**I want to** start with the customer acquisition channel
**So that** I get the full context of how someone will arrive at my product and design their onboarding experience to get them to an "aha" moment as quickly as possible

http://tractionbook.com/ describes the "Bullseye framework"
https://trello.com/b/kpPww9qv/growth-template contains a template for a 1-2 hour exercise

**Comment by tysongach** [comment]
Closing; [this repo has been deprecated](https://github.com/thoughtbot/design-sprint/commit/cdf3f3802adb58033ede2a7c2c45fe97e5601e51).
